# Generated by Django 3.2.16 on 2022-10-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
