# Generated by Django 4.1 on 2022-10-08 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="catagory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_img", models.ImageField(blank=True, null=True, upload_to="")),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("education", models.CharField(blank=True, max_length=200, null=True)),
                ("visit", models.IntegerField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("time1", models.TimeField(blank=True, null=True)),
                ("time2", models.TimeField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                (
                    "speciality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catagory",
                        to="main.catagory",
                    ),
                ),
            ],
        ),
    ]
