# Generated by Django 4.1 on 2022-10-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="speciality",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
