# Generated by Django 4.1 on 2022-10-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_doctors_speciality"),
    ]

    operations = [
        migrations.RemoveField(model_name="doctors", name="time2",),
    ]
