# Generated by Django 4.1 on 2022-10-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_doctors_time2"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctors",
            name="time2",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
