# Generated by Django 4.1 on 2022-10-11 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_doctors_time2"),
    ]

    operations = [
        migrations.CreateModel(
            name="profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_img",
                    models.ImageField(
                        blank=True,
                        default="profiles/default.png",
                        null=True,
                        upload_to="profiles/",
                    ),
                ),
                ("Name", models.CharField(max_length=20)),
                ("Email", models.EmailField(max_length=254, null=True)),
                ("Date_of_Birth", models.DateField(null=True)),
                ("PhoneNumber", models.CharField(max_length=15, null=True)),
                (
                    "Gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
