# Generated by Django 4.1 on 2022-10-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="Date_of_Birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="Email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="Name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="PhoneNumber",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
