# Generated by Django 4.1 on 2022-10-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_profile_date_of_birth_alter_profile_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("datetime", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
