# Generated by Django 3.2.16 on 2022-10-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='designation',
        ),
    ]
