# Generated by Django 4.1 on 2022-10-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_catagory_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctors",
            name="day",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
