# Generated by Django 4.1 on 2022-10-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cabininfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roomType", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "Description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("avalability", models.IntegerField(blank=True, null=True)),
                ("rent", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
