# Generated by Django 4.1 on 2022-10-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabin", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cabininfo", old_name="avalability", new_name="available",
        ),
        migrations.RenameField(
            model_name="cabininfo", old_name="Description", new_name="description",
        ),
    ]
