# Generated by Django 4.1 on 2022-10-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabin", "0002_rename_avalability_cabininfo_available_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cabinbooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("d_name", models.CharField(blank=True, max_length=200, null=True)),
                ("nid", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "phoneNumber",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("roomType", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
