# Generated by Django 4.1 on 2022-10-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabin", "0003_cabinbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="cabininfo",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
